### PR TITLE
cleanup.py

### PR DESCRIPTION
**Pull request by MonkeyTedBaker**
Only supports mysql and pgsql.

Run light cleanup (sightings, fort_sightings, mystery_sightings, raids) runs every minute.
Heavy cleanup (spawnpoints) runs every hour.

### Commands
```
# Help
python3.6 cleanup.py -h

# Show cron commands
python3.6 cleanup.py -sh

# Set cron
python3.6 cleanup.py -sc

# Unset cron
python3.6 cleanup.py -uc

# Run light cleanup once (sightings, fort_sightings, mystery_sightings, raids)
python3.6 cleanup.py --light

# Run heavy cleanup once (spawnpoints)
python3.6 cleanup.py --heavy
```

### Log
Cleanup log will be recorded in logs/cron.log

### Config

```
### Cleanup
## Max number of rows to delete in each execution per table. Not recommended to set it too high. It will choke the DB.
# CLEANUP_LIMIT = 100000

## Table specific cleanup times. Set -1 to disable
# CLEANUP_RAIDS_OLDER_THAN_X_HR = 6.0
# CLEANUP_SIGHTINGS_OLDER_THAN_X_HR = 6.0
# CLEANUP_SPAWNPOINTS_OLDER_THAN_X_HR = 24.0
# CLEANUP_FORT_SIGHTINGS_OLDER_THAN_X_HR = 6.0
# CLEANUP_MYSTERY_SIGHTINGS_OLDER_THAN_X_HR = 24.0
```

### CODE REVIEW

**Comment by captainmedic** [comment]
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cleanup.py", line 114, in <module>
    main()
  File "cleanup.py", line 106, in main
    Cleanup.light()
  File "/monocle/cleanup.py", line 71, in light
    cleanup_with_temp_table("raids", now - (conf.CLEANUP_RAIDS_OLDER_THAN_X_HR * 3600), time_col="time_spawn")
  File "/monocle/cleanup.py", line 44, in cleanup_with_temp_table
    'limit': limit,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "AS"
LINE 2:         CREATE TEMPORARY TABLE IF NOT EXISTS raids_tmp AS (
                                                               ^
 [SQL: '\n        CREATE TEMPORARY TABLE IF NOT EXISTS raids_tmp AS (\n          SELECT t.id\n          FROM raids t\n          WHERE t.time_spawn IS NULL OR t.time_spawn < %(time)s\n          LIMIT %(limit)s \n        )'] [parameters: {'time': 1507165042.4321198, 'limit': 100000}]
`
Stack trace

**Comment by MonkeyTedBaker** [comment]
what version of pgsql are you using?

**Comment by captainmedic** [comment]
PostgreSQL 9.2.23

**Comment by MonkeyTedBaker** [comment]
Can you try removing `AS` from this line and see if it works?
```
https://github.com/MonkeyTedBaker/Monocle/pull/39/files#diff-a4e7ee6f1ab174e7788219d09549663aR37
```

**Comment by captainmedic** [comment]
```The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cleanup.py", line 114, in <module>
    main()
  File "cleanup.py", line 106, in main
    Cleanup.light()
  File "/monocle/cleanup.py", line 71, in light
    cleanup_with_temp_table("raids", now - (conf.CLEANUP_RAIDS_OLDER_THAN_X_HR * 3600), time_col="time_spawn")
  File "/monocle/cleanup.py", line 44, in cleanup_with_temp_table
    'limit': limit,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "SELECT"
LINE 3:           SELECT t.id
                  ^
 [SQL: '\n        CREATE TEMPORARY TABLE IF NOT EXISTS raids_tmp (\n          SELECT t.id\n          FROM raids t\n          WHERE t.time_spawn IS NULL OR t.time_spawn < %(time)s\n          LIMIT %(limit)s\n        )'] [parameters: {'time': 1507166099.3626952, 'limit': 100000}]
```
New stack trace

**Comment by captainmedic** [comment]
Issue appears to be related to outdated DB that is near it's EOL. Updating to a current version resolved problem.
```[2017-10-05 04:02:59][    INFO][cleanup] Performing light cleanup.
[2017-10-05 04:02:59][    INFO][monocle.cleanup] Cleaning up raids...
[2017-10-05 04:02:59][    INFO][monocle.cleanup] => Done. 93 raids deleted.
[2017-10-05 04:02:59][    INFO][monocle.cleanup] Cleaning up fort_sightings...
[2017-10-05 04:02:59][    INFO][monocle.cleanup] => Done. 33 fort_sightings deleted.
[2017-10-05 04:02:59][    INFO][monocle.cleanup] Cleaning up mystery_sightings...
[2017-10-05 04:02:59][    INFO][monocle.cleanup] => Done. 0 mystery_sightings deleted.
[2017-10-05 04:02:59][    INFO][monocle.cleanup] Cleaning up sightings...
[2017-10-05 04:03:01][    INFO][monocle.cleanup] => Done. 100000 sightings deleted.
[2017-10-05 04:03:01][    INFO][monocle.cleanup] Light cleanup done.
```

**Pull request merged**
