### PR TITLE
[WIP]Low Account Level Notifications

### PR DESCRIPTION
**Pull request by captainmedic**
This will need testing. I can confirm it works for initial notification, but I was unable to test with account refreshment, if it resets and starts over when it begins to decrease.

In essence this should allow you to receive a push notification to Discord when the acct clean level goes below the threshold you specify. This is an attempted solution for issue #51

### CODE REVIEW

**Comment by phonezawphyo** [comment]
Thanks. Pls make sure to make use of ‘common’ table in order to send the notification only once across multiple instances.

**Comment by MonkeyTedBaker** [comment]
Thanks. Pls make sure to make use of ‘common’ table in order to send the notification only once across multiple instances.

**Comment by captainmedic** [comment]
Hmm. So I am looking at the code. It does call the DB-wide accounts info as it stands now. Where I am running into an issue is that even though we have the common table, at least for me, its timestamp gets updated I believe every 5 minutes, and in my case I only ever have the one active timestamp, so I can't really think of a way to sync the notification across all instances. I thought about adding a timestamp comparison, prior to sending a notification, but the same can be accomplished by changing the interval of ACCT_REFRESH. The only way I could possibly think about syncing across multiple instances would be to maybe add a new column to the db with the timestamp the last message was sent, that way we could have all instances check prior to trying a notification. Let me know if you have any thoughts or if my thought process is wrong, a little tired right now, heh

**Comment by MonkeyTedBaker** [comment]
Yeah. This is very close.
I changed account refresh rate to every 1 min instead of 5 in `swap` branch, pending merge.
You would need to save `low_acc_noti_sent_at` in `common` table.
Before sending webhook, check the value of that key and only send the note if the time diff is more than like 6 or 12 hr. And update low_acc_noti_sent_at once after sending.
Make sure to use lock when getting the `common` record for it.

**Comment by MonkeyTedBaker** [comment]
ACCT_REFRESH is probably not needed. I think it will just be an extra config that confuses users.

**Pull request closed without merging**
